In [79]:
import pandas as pd
from datetime import date

In [2]:
b = 4
a = 22
c = 33
delta = b** - 4*a*c

In [3]:
delta

2.8359375

In [4]:
employee_name = input("Name: ")
salary = int(input("Salary: "))
bonus = int(input("Bonus: "))

print(f"employee_name: {employee_name}")
print(f'Salary: {salary}')
print(f"Bonus: {bonus}")
print(f"Full Salary: {salary + bonus}")

employee_name:
Salary: 10000
Bonus: 10
Full Salary: 10010

### Bài tập 2

In [6]:
customer_name = input("Enter customer name: ")
total_bill = float(input("Enter total bill "))
discount = float(input("Discount: "))
tips = total_bill * (discount / 100)
pay_bill = total_bill + tips

print(f"Customer name: {customer_name}")
print(f'tips: {tips} VND')
print(f'Total bill: {total_bill} VND')
print(f"Pay bill: {pay_bill} VND")

Customer name: Vũ
tips: 10000.0 VND
Total bill: 100000.0 VND
Pay bill: 110000.0 VND

In [ ]:
chi_phi_ban = int(input("Chi Phi Ban: "))
chi_phi_van_chuyen = int(input("Chi Phí Vận Chuyển: "))
ty_le_loi_nhuan = float(input("Ty le loi nhuan: "))

gia_ban = (chi_phi_ban + chi_phi_van_chuyen) / (1 - ty_le_loi_nhuan)
print(gia_ban)

22333333.333333332

## EXCEL

In [7]:
import openpyxl as xl

In [9]:
excel_file = "user_information.xlsx"
wb = xl.Workbook()
ws = wb.active
ws.title = "User Information"
headers = ["Full name", "Birth of Date", "Email", "Phone number", "Job", "Marriage description"]
ws.append(headers)

In [ ]:
ws.append([
    "Lê Thiên Vũ",
    "27/07/1995",
    "thienvu@gmail.com",
    "0777073544",
    "dev",
    "no"
])
wb.save("user_information.xlsx")

In [16]:
pd.read_excel("user_information.xlsx")

,Full name,Birth of Date,Email,Phone number,Job,Marriage description
0,Lê Thiên Vũ,27/07/1995,thienvu@gmail.com,777073544,dev,no
1,Lê Thiên Vũ,27/07/1995,thienvu@gmail.com,777073544,dev,no

## Bài Tập 3

In [ ]:
data_excel_file = "data.xlsx"
work_book = xl.Workbook()
work_sheet = work_book.active
work_sheet.title = 'Danh sách sản phẩm'
work_sheet.append(['Mã sản phẩm', 'Tên sản phẩm', 'Giá bán'])

In [19]:
work_sheet.append(['1', 'iPhone', '1000$'])
work_sheet.append(['2', 'galaxy S25', '1200$'])
work_sheet.append(['3', 'Macbook Pro', '2000$'])

In [24]:
work_book.save(data_excel_file)

In [23]:
pd.read_excel("data.xlsx")

   Mã sản phẩm Tên sản phẩm Giá bán
0            1       iPhone   1000$
1            2   galaxy S25   1200$
2            3  Macbook Pro   2000$

In [27]:
employee_list = "employee_list.xlsx"
wb = xl.Workbook()
ws = wb.active
ws.title = "Danh sách nhân viên"
headers = ["Mã nhân viên", "Họ và Tên", "Chức vụ", "Mức lương"]
ws.append(headers)

In [28]:
wb.save(employee_list)

In [29]:
pd.read_excel(employee_list)

Empty DataFrame
Columns: [Mã nhân viên, Họ và Tên, Chức vụ, Mức lương]
Index: []

In [56]:
doanh_thu = float(input("Doanh thu hàng năm: "))
chi_phi = float(input("Chi phí giá vốn: "))
loi_nhuan_gop = doanh_thu - chi_phi
ty_suat_loi_nhuan = loi_nhuan_gop / doanh_thu

print(f'Lợi Nhuận Gộp: {loi_nhuan_gop}$')
print(f'Tỷ suất lợi nhuận: {ty_suat_loi_nhuan}$')

Lợi Nhuận Gộp: 80000.0$
Tỷ suất lợi nhuận: 0.8$

In [64]:
excel_loi_nhuan = "loi_nhuan.xlsx"
ws.title = "Lợi nhuận công ty"
ws.append([doanh_thu, chi_phi, loi_nhuan_gop, ty_suat_loi_nhuan])
wb.save(excel_loi_nhuan)

In [60]:
pd.read_excel(excel_loi_nhuan)

   Doanh thu  Chi Phí  Lợi Nhuận Gộp  Tỷ suất lợi nhuận
0   100000.0  20000.0        80000.0                0.8
1   100000.0  20000.0        80000.0                0.8

In [62]:
loi_nhuan_hien_tai = 50000
ty_le_tang_truong = 5
years = 5
future = loi_nhuan_hien_tai * (1 + ty_le_tang_truong) ^ years
future

300005

In [76]:
excel_chuyen_doi_ty_gia = "ty_gia.xlsx"
wb = xl.Workbook()
ws = wb.active
ws.title = "Chuyển đổi tỷ giá"
headers = ["Ngày nhập", "VND", "USD", "EUR", "GBD"]
ws.append(headers)
wb.save(excel_chuyen_doi_ty_gia)

In [ ]:
vnd = float(input("Giá tiền vnd"))
usd = vnd / 26442
eur = vnd / 30942.98
gbp = vnd / 35330.43

ws.append([date.today(), vnd, usd, eur, gbp])
wb.save(excel_chuyen_doi_ty_gia)

In [81]:
pd.read_excel(excel_chuyen_doi_ty_gia)

             Ngày nhập       VND          USD         EUR         GBD
0           22/06/2026  30000000  1134.558657  969.525236  849.126376
1  2026-06-22 00:00:00   1000000    37.818622   32.317508   28.304213

In [82]:
hours = float(input("Số giờ làm việc: "))
month = int(input("Tháng: "))
luong = int(input("luong: "))
luong_toi_thieu = 0
if month == 8 or month == 12 and hours <= 40:
    luong_toi_thieu = hours * luong
elif hours <= 20 and month != 8 and month != 12:
    luong_toi_thieu = hours * luong
    
luong_toi_thieu

780.0

In [85]:
luong_1_gio = int(input("Lương 1 giờ"))
so_gio_lam = int(input("Số giờ làm: "))
luong_bonus = 0
luong_tong_gio = 0

if so_gio_lam > 40:
    so_gio_du = so_gio_lam - 40 
    luong_bonus = so_gio_du * 2 * luong_1_gio
    tong_luong = 40 * luong_1_gio + luong_bonus
elif so_gio_lam <= 40:
    tong_luong = so_gio_lam * luong_1_gio
    
tong_luong

5000

In [86]:
kpi = float(input("Nhập KPI: "))
min_result = float(input("Nhập kết quả tối thiểu: "))
result = float(input("Nhập doanh số thực tế"))
base_salary = float(input("Nhập lương cơ bản"))

thu_nhap = 0

if min_result <= result >= kpi:
    thu_nhap = base_salary + base_salary * 0.2
    print(f"Lương: {thu_nhap}")
if min_result <= result <= kpi:
    thu_nhap = base_salary
    print(f"Lương: {thu_nhap}")
if min_result >= result:
    print("Warning")

Lương: 8.4

In [88]:
diem = float(input("Điểm học sinh:"))
xep_loai = ""

if diem >= 9.0:
    xep_loai = "Xuất xắc"
elif 8.0 <= diem < 9.0:
    xep_loai = "Gioi"
elif 6.5 <= diem < 8.0:
    xep_loai = "Khá"
elif 5.0 <= diem < 6.5:
    xep_loai = "TB"
else:
    xep_loai = "Yếu"
    
print(f"Xếp loại học sinh: {xep_loai}")

Xếp loại học sinh: Yếu