# Homework Chapter 1

In [3]:
import openpyxl as ol
import pandas as pd

## Bài tập trên lớp
### Bài 1

In [4]:
doanh_thu = float(input("Doanh thu hàng năm: "))
chi_phi = float(input("Chi phí giá vốn: "))
loi_nhuan_gop = doanh_thu - chi_phi
ty_suat_loi_nhuan = loi_nhuan_gop / doanh_thu

print(f'Lợi Nhuận Gộp: {loi_nhuan_gop}$')
print(f'Tỷ suất lợi nhuận: {ty_suat_loi_nhuan}$')

excel_doanh_thu = "doanh_thu.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Doanh thu"
headers = ["Doanh thu hằng năm", "Chi phí giá vốn", "Lợi nhuận Gộp", "Tỷ xuất lợi nhuận gộp"]
ws.append(headers)
data_doanh_thu = [doanh_thu, chi_phi, loi_nhuan_gop, ty_suat_loi_nhuan]
ws.append(data_doanh_thu)
wb.save(excel_doanh_thu)

Lợi Nhuận Gộp: 80000.0$
Tỷ suất lợi nhuận: 0.8$

In [5]:
pd.read_excel(excel_doanh_thu)

   Doanh thu hằng năm  Chi phí giá vốn  Lợi nhuận Gộp  Tỷ xuất lợi nhuận gộp
0              100000            20000          80000                    0.8

### Bài 2

In [ ]:
loi_nhuan_hien_tai = float(input("Lợi nhuận hiện tại: "))
ty_le_tang_truong = float(input("Tỷ lệ tăng trưởng")) / 100
years = float(input("Kê hoạch sau bao nhiêu năm: "))
loi_nhuan_tuong_lai = loi_nhuan_hien_tai * (1 + ty_le_tang_truong) ** years

excel_loi_nhuan_tuong_lai = "Lợi nhuận tương lai.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Lợi nhuận tương lai"
headers = ["Lợi nhuận hiện tại", "Tỷ lệ tăng trưởng", "Năm", "Lợi nhuận tương lai"]
ws.append(headers)
data_loi_nhuan = [loi_nhuan_hien_tai, ty_le_tang_truong, years, loi_nhuan_tuong_lai]
ws.append(data_loi_nhuan)
wb.save(excel_loi_nhuan_tuong_lai)

In [11]:
pd.read_excel(excel_loi_nhuan_tuong_lai)

   Lợi nhuận hiện tại  Tỷ lệ tăng trưởng  Năm  Lợi nhuận tương lai
0               50000               0.05    5         63814.078125

### Bài 3

In [30]:
so_co_phan = float(input("Số cổ phần: "))
gia_tri_loi_nhuan = float(input("Giá trì lợi nhuận trên mỗi cổ phần: "))
ty_le_co_tuc = float(input("Tỷ lệ cổ tức cho mỗi cổ phần: ")) / 100
tong_tien_co_tuc = so_co_phan * gia_tri_loi_nhuan * ty_le_co_tuc

excel_tong_tien_co_tuc = "Tổng tiền cổ tức.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Tổng tiền cổ tức"
headers = ["Số cổ phần", "Giá trị lợi nhuận", "Tỷ lệ cổ tức", "Tổng tiền cổ tức"]
ws.append(headers)
data_co_tuc = [so_co_phan, gia_tri_loi_nhuan, ty_le_co_tuc, tong_tien_co_tuc]
ws.append(data_co_tuc)
wb.save(excel_tong_tien_co_tuc)

In [31]:
pd.read_excel(excel_tong_tien_co_tuc)

   Số cổ phần  Giá trị lợi nhuận  Tỷ lệ cổ tức  Tổng tiền cổ tức
0        1200                 20          0.15              3600

### Bài 4

In [34]:
b1 = int(input("b1 items: "))
c1 = int(input("c1 price: "))
e1 = int(input("e1 items left: "))
b2 = int(input("b2 items: "))
c2 = int(input("c2 price: "))
e2 = int(input("e2 items left: "))

doanh_thu_thuc_te = (b1 - e1) * c1 + (b2 - e2) * c2
doanh_thu_toi_da = (b1 * c1) + (b2 * c2)
excel_doanh_thu_san_pham = "Doanh thu sản phẩm.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Doanh thu sản phẩm"
headers = [
    "Số mặt hàng một b1", 
    "Giá của một b1", 
    "Số mặt hàng loại 1 còn lại", 
    "Số mặt hàng hai",
    "Giá của một b2",
    "Số mặt hàng loại 2 còn lại",
    "Doanh thu thực tế",
    "Doanh thu tối đa:"
    ]
ws.append(headers)
data_san_pham = [b1, c1, e1, b2, c2, e2, doanh_thu_thuc_te, doanh_thu_toi_da]
ws.append(data_san_pham)
wb.save(excel_doanh_thu_san_pham)

In [35]:
pd.read_excel(excel_doanh_thu_san_pham)

,Số mặt hàng một b1,Giá của một b1,Số mặt hàng loại 1 còn lại,Số mặt hàng hai,Giá của một b2,Số mặt hàng loại 2 còn lại,Doanh thu thực tế,Doanh thu tối đa:
0,20,10000,5,25,20000,8,490000,700000

### Bài 5

In [37]:
c = int(input("Number of cents: "))
dollar = c * 0.01
print(f"Dollar: {dollar}$, \ncent: {c}¢")

excel_cent_to_dollar = "cent_to_dollar.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Convert Cent to Dollar"
headers = ["Cent", "Dollar"]
ws.append(headers)
data = [c, dollar]
ws.append(data)
wb.save(excel_cent_to_dollar)

Dollar: 0.5$,
cent: 50¢

In [38]:
pd.read_excel(excel_cent_to_dollar)

   Cent  Dollar
0    50     0.5

# Bài Tập Về Nhà
### Bài 1

In [ ]:
chi_phi_dau_tu = float(input("Chi phí đầu tư: "))
thu_nhap_rong = float(input("Thu nhập ròng: "))
roi = (thu_nhap_rong / chi_phi_dau_tu) * 100
print(f'ROI: {roi:.2f}%')

wb = ol.Workbook()
ws = wb.active
excel_roi = "roi.xlsx"
ws.title = "ROI"
headers = ["Thu nhập ròng", "Chi phí đầu tư", "ROI"]
ws.append(headers)
data = [thu_nhap_rong, chi_phi_dau_tu, f"{roi:.2f}%"]
ws.append(data)
wb.save(excel_roi)

ROI: 133.33333333333331%

In [42]:
pd.read_excel(excel_roi)

   Thu nhập ròng  Chi phí đầu tư      ROI
0          20000           15000  133.33%

### Bài 2

In [45]:
vay_ngan_hang = float(input("Số tiền vay ngân hàng: "))
lai_xuat_hang_nam = float(input("Lãi xuất hằng năm: ")) / 100 / 12
months = int(input("Trả trong vòng bao nhiêu tháng: "))

tra_gop_hang_thang = (vay_ngan_hang * lai_xuat_hang_nam * (1 + lai_xuat_hang_nam)**months) / ((1 + lai_xuat_hang_nam)**months -1)
print(f'Số tiền trả góp: {tra_gop_hang_thang:.2f}')

excel_tra_gop = "tra_gop.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Trả góp ngân hàng"
headers = ['Số tiền vay ngân hàng', 'Lãi xuất hằng năm', 'Số tháng', 'Trả góp hàng tháng']
ws.append(headers)
data = [vay_ngan_hang, lai_xuat_hang_nam, months, f'{tra_gop_hang_thang:.2f}']
ws.append(data)
wb.save(excel_tra_gop)

Số tiền trả góp: 4465863.79

In [46]:
pd.read_excel(excel_tra_gop)

   Số tiền vay ngân hàng  Lãi xuất hằng năm  Số tháng  Trả góp hàng tháng
0               50000000           0.010833        12          4465863.79

### Bài 3

In [50]:
usd = float(input("Số tiền USD: "))
ty_gia_usd = float(input("Tỷ giá USD: "))
vnd = usd * ty_gia_usd
print(f'USD: {usd}$ to VND:{vnd}d')

excel_chuyen_doi_ty_gia = "chuyen_doi_ty_gia.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Chuyển đổi tỷ giá"
headers = ["USD", " Tỷ Giá USD", "VND"]
ws.append(headers)
data = [f'{usd}$', f'{ty_gia_usd}vnd', f'{vnd}đ']
ws.append(data)
wb.save(excel_chuyen_doi_ty_gia)

USD: 100.0$ to VND:2600000.0d

In [51]:
pd.read_excel(excel_chuyen_doi_ty_gia)

      USD  Tỷ Giá USD         VND
0  100.0$  26000.0vnd  2600000.0đ

### Bài 4

In [54]:
k = int(input("Number of knuts: "))
s = k / 29
g = s / 17
print(f'Galleons: {g:.2f} \nSickles: {s:.2f} \nKnuts: {k}')

excel_wizzard_currency = "wizzard_currency.xlsx"
wb = ol.Workbook()
ws = wb.active
ws.title = "Wizzard Currency"
headers = ["Galleons", " Sickles", "Knuts"]
ws.append(headers)
data = [f'{g:.2f}', f'{s:.2f}', f'{k}']
ws.append(data)
wb.save(excel_wizzard_currency)

Galleons: 25195.64
Sickles: 428325.90
Knuts: 12421451

In [55]:
pd.read_excel(excel_wizzard_currency)

   Galleons   Sickles     Knuts
0  25195.64  428325.9  12421451